// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFJwf9G2NwDwdUXo0QmMxBLQeo3Dmr_9Y',
    appId: '1:48650323494:web:4b8e31eed2c9006d01c8e7',
    messagingSenderId: '48650323494',
    projectId: 'flutter-learn-554bd',
    authDomain: 'flutter-learn-554bd.firebaseapp.com',
    databaseURL: 'https://flutter-learn-554bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-learn-554bd.firebasestorage.app',
    measurementId: 'G-X3B5KNBWKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmlydIFgdTKgTtW5BzIbQBcfG-JxpysKg',
    appId: '1:48650323494:android:91788e0e286af3c701c8e7',
    messagingSenderId: '48650323494',
    projectId: 'flutter-learn-554bd',
    databaseURL: 'https://flutter-learn-554bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-learn-554bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNbsJQQFg3A1o3767Lp3ToL5YmviHVh9c',
    appId: '1:48650323494:ios:c8144df2a116f3f001c8e7',
    messagingSenderId: '48650323494',
    projectId: 'flutter-learn-554bd',
    databaseURL: 'https://flutter-learn-554bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-learn-554bd.firebasestorage.app',
    iosClientId: '48650323494-s74mt5riatb4svsl02ke8bp5np1aiik4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNbsJQQFg3A1o3767Lp3ToL5YmviHVh9c',
    appId: '1:48650323494:ios:c8144df2a116f3f001c8e7',
    messagingSenderId: '48650323494',
    projectId: 'flutter-learn-554bd',
    databaseURL: 'https://flutter-learn-554bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-learn-554bd.firebasestorage.app',
    iosClientId: '48650323494-s74mt5riatb4svsl02ke8bp5np1aiik4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFJwf9G2NwDwdUXo0QmMxBLQeo3Dmr_9Y',
    appId: '1:48650323494:web:3fc408b7864e247801c8e7',
    messagingSenderId: '48650323494',
    projectId: 'flutter-learn-554bd',
    authDomain: 'flutter-learn-554bd.firebaseapp.com',
    databaseURL: 'https://flutter-learn-554bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-learn-554bd.firebasestorage.app',
    measurementId: 'G-WDXZ2MTNGX',
  );
}
